name: 'katapay_project'
version: '1.0'
config-version: 2

profile: 'katapay_project'

model-paths: ["models"]
macro-paths: ["macros", "dbt_packages/dbt_synth_data/macros"]
seed-paths: ["data"]
target-path: "target"
clean-targets: ["target"]

models:
  katapay_project:
    synth:
      +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table

dispatch:
  - macro_namespace: dbt_synth_data
    search_order: [katapay_project, dbt_synth_data]

seeds:
  katapay_project:
    holiday_list:
      column_types:
        date: date
        holiday_name: text
