
version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: katapay_postgres
    environment:
      POSTGRES_DB: katapay
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    ports:
      - "5440:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  superset:
    image: apache/superset:3.0.0
    container_name: katapay_superset
    environment:
      - SUPERSET_DATABASE_URI=postgresql+psycopg2://airflow:airflow@postgres:5432/katapay
      - SUPERSET_SECRET_KEY=3B1blsL8UOq+e1tcMdh7qZ1aG5DcVP8qThFV4mPdE7o=
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py
    command: >
      /bin/sh -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin || true &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
      "

volumes:
  pg_data:
  airbyte_data:
  airbyte_db_data:
  superset_home:
